### ISSUE TITLE
raise KeyError("Spider not found: %s" % spider_name)

### ISSUE THREAD

**Issue by Omid-r** [laveeshr/darkWebBot#1]
Hello laveeshr 
Thanks for your Crawler..
I'm sure I do every thing right..but in the end I take this error...
raise KeyError("Spider not found: %s" % spider_name)
Please guide me..

**Comment by laveeshr** [comment]
Hi Omid-r,
The name of the spider was wrong somehow, sorry for that.
Pull the code and try running it again, should work

**Comment by laveeshr** [comment]
Issue resolved. Just pull the latest code and follow the instructions given. Should run without errors.
