### ISSUE TITLE
testpolipo.setting Erorr

### ISSUE THREAD

**Issue by Omid-r** [laveeshr/darkWebBot#2]
Hi guys..
Please Help me to handeling this Erorr..
<img width="627" alt="screen shot 1396-04-14 at 10 16 03" src="https://user-images.githubusercontent.com/28532153/27850648-448f4612-616b-11e7-8c96-eeec8802fbae.png">

**Comment by laveeshr** [comment]
Issue resolved. Just pull the latest code and follow the instructions given. Should run without errors.
