### ISSUE TITLE
a problem in running : ImportError: No module named testPolipo.settings

### ISSUE THREAD

**Issue by zaranmd** [laveeshr/darkWebBot#3]
Hi @laveeshr ...Thank you for sharing this project...
I did all of the steps that you've said...
but finally i faced with the error which is :
~/Downloads/darkWebBot/testPolipo/testPolipo$ scrapy crawl darkWebBot -o items.json -t json
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/cmdline.py", line 109, in execute
    settings = get_project_settings()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/project.py", line 68, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/usr/local/lib/python2.7/dist-packages/scrapy/settings/__init__.py", line 292, in setmodule
    module = import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named testPolipo.settings

i have some questions:
1- does the version of the solr affect? in mine is solr6.6.0.
2- what do you mean by : sudo mv darkWebBot/config ? Replacing the config file of darkWebBot with polipo's?
3- as i am beginner in scrapy and python, plz guide me more...

**Comment by laveeshr** [comment]
1- I dont think this is a solr issue. Scrapy is unable to locate the settings file inside the project, maybe there's a mismatch with the name of the project or something. Just look into how to import the settings page and that should do it I guess.
2- This command basically moves the provided config file and replaces it with the default file. Follow the exact steps as provided (like the previous step it asks you to change the directory to the config location).

**Comment by laveeshr** [comment]
Issue resolved. Just pull the latest code and follow the instructions given. Should run without errors.
